### ISSUE TITLE
Try not to restrict dependency versions

### ISSUE THREAD

**Issue by wangkuiyi** [jaywonchung/BERT4Rec-VAE-Pytorch#10]
Dependencies in `requirements.txt` all have specified versions. Some of them are quite out of date. I realized that with the most recent version of them, we can run the program all good. How about we remove those version constraints?

**Comment by jaywonchung** [comment]
Hi. Thanks for the suggestion.

I disagree because removing versions altogether will always point to the latest version and will one day break. The requirements.txt currently serves the function of a dependency lock, representing a package version snapshot that is old but guaranteed to work.

**Comment by wangkuiyi** [comment]
@jaywonchung Good point! How about update to the latest version that we know works with the program?

**Comment by jaywonchung** [comment]
That'll be great. Could you update your PR with the versions you checked? I'll merge right away.

**Comment by kappek** [comment]
It would also be great if you could add python and cuda versions to the setup file.
