### ISSUE TITLE
bert implementation

### ISSUE THREAD

**Issue by shainaraza** [jaywonchung/BERT4Rec-VAE-Pytorch#2]
I am just wondering like yours code, we can have our own implementation of BERT and that means to say we can implement of without going into the parent library https://github.com/google-research/bert

**Comment by jaywonchung** [comment]
Sorry, I'm having difficulty understanding your question. 

Besides, yes, this repository doesn't directly utilize the google repository you mentioned.

**Comment by shainaraza** [comment]
thanks, great work

**Comment by shainaraza** [comment]
sorry for bothering you again, we do not sequence (text) in bert as in this implementation (just for my information, as I am confused with actual implementation where they is sequence)

**Comment by jaywonchung** [comment]
Well, the BERT part was written by @SungMinCho, so tributes to him :)

To elaborate, BERT was originally proposed in the field of natural language processing. It was the paper BERT4Rec that proposed to adopt BERT to the sequential recommendation task.

Closing the issue! Feel free to re-open when needed.

**Comment by shainaraza** [comment]
thanks you very much
really great work in this repository
