### ISSUE TITLE
where can I find the results such as predictions made?

### ISSUE THREAD

**Issue by shainaraza** [jaywonchung/BERT4Rec-VAE-Pytorch#4]

**Comment by jaywonchung** [comment]
Refer to [this line](https://github.com/jaywonchung/BERT4Rec-VAE-Pytorch/blob/f66f2534ebfd937778c7174b5f9f216efdebe5de/trainers/bert.py#L34), which is called by the `validate` and `test` methods in each model.
You will have to modify the code to save the predictions in a persistent form, perhaps with `torch.save`.

Sorry for the delayed reponse.
Jaewon.
