### ISSUE TITLE
Can you please add licence to the repo?

### ISSUE THREAD

**Issue by hoxmark** [jaywonchung/BERT4Rec-VAE-Pytorch#5]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided. 

Per GitHub docs on licensing:
> Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Thanks in advance!

**Comment by jaywonchung** [comment]
I've just attached the GPL-3.0 license to the repository.

Thank you for your kind suggestion!
